ChuyenDeASPNET/Areas/Admin/Controllers/ProductController.cs
using ChuyenDeASPNET.Context;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChuyenDeASPNET.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        ASPNETEntities3 objASPNETEntities = new ASPNETEntities3();
        // GET: Admin/Product
        public ActionResult Index()
        {
            var lstProduct = objASPNETEntities.Products.ToList();
            return View(lstProduct);
        }
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(objASPNETEntities.Categories, "CategoryID", "CategoryName");
            ViewBag.BrandID = new SelectList(objASPNETEntities.Brands, "BrandID", "BrandName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product, HttpPostedFileBase ProductImage)
        {
            if (ModelState.IsValid)
            {
                if (ProductImage != null && ProductImage.ContentLength > 0)
                {
                    // Lưu hình ảnh vào thư mục Images (hoặc thư mục bạn muốn)
                    var fileName = Path.GetFileName(ProductImage.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images/items/"), fileName);
                    ProductImage.SaveAs(path);

                    // Lưu tên file hình ảnh vào thuộc tính ProductImage
                    product.ProductImage = fileName;
                }

                objASPNETEntities.Products.Add(product);
                objASPNETEntities.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(objASPNETEntities.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewBag.BrandID = new SelectList(objASPNETEntities.Brands, "BrandID", "BrandName", product.BrandID);

            return View(product);
        }
        // GET: Admin/Product/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null) return HttpNotFound();

            var product = objASPNETEntities.Products.Find(id);
            if (product == null) return HttpNotFound();

            ViewBag.CategoryID = new SelectList(objASPNETEntities.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewBag.BrandID = new SelectList(objASPNETEntities.Brands, "BrandID", "BrandName", product.BrandID);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                objASPNETEntities.Entry(product).State = System.Data.Entity.EntityState.Modified;
                objASPNETEntities.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(objASPNETEntities.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewBag.BrandID = new SelectList(objASPNETEntities.Brands, "BrandID", "BrandName", product.BrandID);
            return View(product);
        }

        // GET: Admin/Product/Delete/5
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null) return HttpNotFound();

            var product = objASPNETEntities.Products.Find(id);
            if (product == null) return HttpNotFound();

            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult ConfirmDelete(int id)
        {
            var product = objASPNETEntities.Products.Find(id);
            if (product == null) return HttpNotFound();

            objASPNETEntities.Products.Remove(product);
            objASPNETEntities.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Admin/Product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null) return HttpNotFound();

            var product = objASPNETEntities.Products.Find(id);
            if (product == null) return HttpNotFound();

            return View(product);
        }

    }
}

ChuyenDeASPNET/Controllers/ProductController.cs
using ChuyenDeASPNET.Context;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChuyenDeASPNET.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        ASPNETEntities3 objASPNETEntities = new ASPNETEntities3();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductDetail(int id)
        {
            var objProduct = objASPNETEntities.Products.Where(n => n.ProductID == id).FirstOrDefault();
            return View(objProduct);
        }
        public ActionResult AllProduct(string currentFilter, string SearchString, int? page)
        {
            var lstProduct = new List<Product>();
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                lstProduct = objASPNETEntities.Products.Where(n => n.ProductName.Contains(SearchString)).ToList();
            }
            else
            {
                lstProduct = objASPNETEntities.Products.ToList();
            }
            ViewBag.CurentFIlter = SearchString;
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            lstProduct = lstProduct.OrderByDescending(n => n.ProductID).ToList();
            return View(lstProduct.ToPagedList(pageNumber, pageSize));
        }
    }
}

ChuyenDeASPNET/Controllers/ShoppingController.cs
using ChuyenDeASPNET.Context;
using ChuyenDeASPNET.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChuyenDeASPNET.Controllers
{
    public class ShoppingController : Controller
    {
        // GET: Shopping
        ASPNETEntities3 objASPNETEntities = new ASPNETEntities3();
        public ActionResult Cart()
        {
            return View((List<CartModel>)Session["cart"]);
        }
        public ActionResult AddtoCart(int id, int quantity)
        {
            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { Product = objASPNETEntities.Products.Find(id), Quantity = quantity });
                Session["cart"] = cart;
                Session["count"] = 1;
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                //kiểm tra sản phẩm có tồn tại trong giỏ hàng chưa???
                int index = isExist(id);
                if (index != -1)
                {
                    //nếu sp tồn tại trong giỏ hàng thì cộng thêm số lượng
                    cart[index].Quantity += quantity;
                }
                else
                {
                    //nếu không tồn tại thì thêm sản phẩm vào giỏ hàng
                    cart.Add(new CartModel { Product = objASPNETEntities.Products.Find(id), Quantity = quantity });
                    //Tính lại số sản phẩm trong giỏ hàng
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                }
                Session["cart"] = cart;
            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
        private int isExist(int id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Product.ProductID.Equals(id))
                    return i;
            return -1;
        }

        public ActionResult Remove(int Id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.Product.ProductID == Id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }

    }
}

ChuyenDeASPNET/Views/Product/AllProduct.cshtml
@{
    ViewBag.Title = "AllProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AllProduct</h2>

@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<ChuyenDeASPNET.Context.Product>
@{
    ViewBag.Title = "Tất cả sản phẩm";
    var totalPrice = Model.Sum(p => Convert.ToDecimal(p.Price));
    var formattedTotalPrice = totalPrice.ToString("C0", System.Globalization.CultureInfo.CreateSpecificCulture("vi-VN"));
}

<section class="section-content padding-y">
    <div class="container">

        <!-- ============================  LỌC PHÍA TRÊN  ================================= -->
        <div class="card mb-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-2"> Bạn đang ở đây: </div> <!-- col.// -->
                    <nav class="col-md-8">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Trang chủ</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Danh sách sản phẩm</li>
                        </ol>
                    </nav> <!-- col.// -->
                </div> <!-- row.// -->
                <hr>
                <div class="row">
                    <div class="col-md-2">Lọc theo</div> <!-- col.// -->
                    <div class="col-md-10">
                        <ul class="list-inline">
                            <li class="list-inline-item mr-3 dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">   Loại nhà cung cấp </a>
                                <div class="dropdown-menu p-3" style="max-width:400px;">
                                    <label class="form-check">
                                        <input type="radio" name="myfilter" class="form-check-input"> Nhà cung cấp tốt
                                    </label>
                                    <label class="form-check">
                                        <input type="radio" name="myfilter" class="form-check-input"> Nhà cung cấp tốt nhất
                                    </label>
                                    <label class="form-check">
                                        <input type="radio" name="myfilter" class="form-check-input"> Nhà cung cấp mới
                                    </label>
                                </div> <!-- dropdown-menu.// -->
                            </li>
                            <li class="list-inline-item mr-3 dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">  Quốc gia </a>
                                <div class="dropdown-menu p-3">
                                    <label class="form-check"> 	 <input type="checkbox" class="form-check-input"> Trung Quốc    </label>
                                    <label class="form-check">   	 <input type="checkbox" class="form-check-input"> Nhật Bản      </label>
                                    <label class="form-check">    <input type="checkbox" class="form-check-input"> Uzbekistan  </label>
                                    <label class="form-check">  <input type="checkbox" class="form-check-input"> Nga     </label>
                                </div> <!-- dropdown-menu.// -->
                            </li>
                            <li class="list-inline-item mr-3 dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tính năng</a>
                                <div class="dropdown-menu">
                                    <a href="" class="dropdown-item">Kháng khuẩn</a>
                                    <a href="" class="dropdown-item">Có nút bấm</a>
                                    <a href="" class="dropdown-item">An toàn hơn</a>
                                </div>
                            </li>
                            <li class="list-inline-item mr-3"><a href="#">Màu sắc</a></li>
                            <li class="list-inline-item mr-3"><a href="#">Kích cỡ</a></li>
                            <li class="list-inline-item mr-3">
                                <div class="form-inline">
                                    <label class="mr-2">Giá</label>
                                    <input class="form-control form-control-sm" placeholder="Tối thiểu" type="number">
                                    <span class="px-2"> - </span>
                                    <input class="form-control form-control-sm" placeholder="Tối đa" type="number">
                                    <button type="submit" class="btn btn-sm btn-light ml-2">Ok</button>
                                </div>
                            </li>
                            <li class="list-inline-item mr-3">
                                <label class="custom-control mt-1 custom-checkbox">
                                    <input type="checkbox" class="custom-control-input">
                                    <div class="custom-control-label">
                                        Sẵn sàng giao hàng
                                    </div>
                                </label>
                            </li>
                        </ul>
                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
        </div> <!-- card.// -->
        <!-- ============================ LỌC PHÍA TRÊN KẾT THÚC ================================= -->

        <header class="mb-3">
            <div class="form-inline">
                <strong class="mr-md-auto">Tìm thấy @Model.Count sản phẩm</strong>
                <select class="mr-2 form-control">
                    <option>Sản phẩm mới nhất</option>
                    <option>Sản phẩm đang thịnh hành</option>
                    <option>Sản phẩm phổ biến nhất</option>
                    <option>Sản phẩm rẻ nhất</option>
                </select>
                <div class="btn-group">
                    <a href="page-listing-grid.html" class="btn btn-light active" data-toggle="tooltip" title="Xem theo danh sách">
                        <i class="fa fa-bars"></i>
                    </a>
                    <a href="page-listing-large.html" class="btn btn-light" data-toggle="tooltip" title="Xem theo lưới">
                        <i class="fa fa-th"></i>
                    </a>
                </div>
            </div>
        </header><!-- sect-heading -->

        <div class="row">
            @foreach (var product in Model)
            {
                <div class="col-md-3">
                    <figure class="card card-product-grid">
                        <div class="img-wrap">
                            <span class="badge badge-danger"> MỚI </span>
                            <img src="~/Content/images/items/@product.ProductImage">
                        </div> <!-- img-wrap.// -->
                        <figcaption class="info-wrap">
                            <a href="#" class="title mb-2">@product.ProductName</a>

                            <p class="mb-2"> @Convert.ToDecimal(product.Price).ToString("C0", System.Globalization.CultureInfo.CreateSpecificCulture("vi-VN"))</p>

                            <p class="text-muted" style="display: -webkit-box; -webkit-box-orient: vertical; overflow: hidden; -webkit-line-clamp: 2; white-space: normal;">@product.ShortDescription</p>

                            <hr>

                            <p class="mb-3">
                                <span class="tag"> <i class="fa fa-check"></i> Đã xác minh</span>
                                <span class="tag"> 2 Năm </span>
                                <span class="tag"> 23 đánh giá </span>
                                <span class="tag"> Nhật Bản </span>
                            </p>

                            <label class="custom-control mb-3 custom-checkbox">
                                <input type="checkbox" class="custom-control-input">
                                <div class="custom-control-label">
                                    Thêm vào so sánh
                                </div>
                            </label>

                            <a href="#" class="btn btn-outline-primary"> <i class="fa fa-envelope"></i> Liên hệ nhà cung cấp </a>

                        </figcaption>
                    </figure>
                </div> <!-- col.// -->
            }

        </div> <!-- row end.// -->

        <nav class="mb-4" aria-label="Điều hướng trang mẫu">
            <ul class="pagination">
                @if (Model.HasPreviousPage)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("AllProduct", new { page = Model.PageNumber - 1, currentFilter = ViewBag.CurrentFilter, sortOrder = ViewBag.CurrentSort })">
                            Trang trước
                        </a>
                    </li>
                }
                else
                {
                    <li class="page-item disabled">
                        <span class="page-link">Trang trước</span>
                    </li>
                }

                @for (int i = 1; i <= Model.PageCount; i++)
                {
                    if (i == Model.PageNumber)
                    {
                        <li class="page-item active">
                            <span class="page-link">@i</span>
                        </li>
                    }
                    else
                    {
                        <li class="page-item">
                            <a class="page-link" href="@Url.Action("AllProduct", new { page = i, currentFilter = ViewBag.CurrentFilter, sortOrder = ViewBag.CurrentSort })">
                                @i
                            </a>
                        </li>
                    }
                }

                @if (Model.HasNextPage)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("AllProduct", new { page = Model.PageNumber + 1, currentFilter = ViewBag.CurrentFilter, sortOrder = ViewBag.CurrentSort })">
                            Trang sau
                        </a>
                    </li>
                }
                else
                {
                    <li class="page-item disabled">
                        <span class="page-link">Trang sau</span>
                    </li>
                }
            </ul>
        </nav>

        <div class="box text-center">
            <p>Bạn có tìm thấy những gì mình cần?</p>
            <a href="index.html" class="btn btn-outline-primary">Quay lại trang trước</a>
        </div>

    </div> <!-- container .// -->
</section>

ChuyenDeASPNET/Views/Product/ProductDetail.cshtml
@model ChuyenDeASPNET.Context.Product

@{
    ViewBag.Title = "Chi tiết";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script type="text/javascript">
    $(function () {
        $("#addtocart").click(function () {
            var model = {};
            // Lấy id sản phẩm
            model.Id = @Model.ProductID;
            // Lấy số lượng đặt hàng
            model.Quantity = $("#ipQuantity").val();
            debugger;
            $.ajax({
                type: "POST",
                url: '@Url.Action("AddtoCart", "Shopping")',
                data:  JSON.stringify(model),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function () {
                    alert("Thêm giỏ hàng thành công!")
                    $('#CartCount').text(@Session["count"] + 1);
                },
                error: function () {
                    alert("Lỗi trong khi thêm vào giỏ hàng!");
                }
            });
            return false;
        });
    });
</script>

<section class="py-3 bg-light">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
            <li class="breadcrumb-item"><a href="#">Chi tiết sản phẩm</a></li>
            <li class="breadcrumb-item active" aria-current="page">@Model.ProductName</li>
        </ol>
    </div>
</section>
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content bg-white padding-y">
    <div class="container">
        <!-- ============================ ITEM DETAIL ======================== -->
        <div class="row">
            <aside class="col-md-6">
                <div class="card">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                            <div> <a href="#"><img src="~/Content/images/items/@Model.ProductImage"></a></div>
                        </div> <!-- slider-product.// -->
                        <div class="thumbs-wrap">
                            <a href="#" class="item-thumb"> <img src="~/Content/images/items/@Model.ProductImage"></a>
                            <a href="#" class="item-thumb"> <img src="~/Content/images/items/@Model.ProductImage"></a>
                            <a href="#" class="item-thumb"> <img src="~/Content/images/items/@Model.ProductImage"></a>
                            <a href="#" class="item-thumb"> <img src="~/Content/images/items/@Model.ProductImage"></a>
                        </div> <!-- slider-nav.// -->
                    </article> <!-- gallery-wrap .end// -->
                </div> <!-- card.// -->
            </aside>
            <main class="col-md-6">
                <article class="product-info-aside">
                    <h2 class="title mt-3">@Model.ProductName</h2>
                    <div class="rating-wrap my-3">
                        <ul class="rating-stars">
                            <li style="width:80%" class="stars-active">
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </li>
                            <li>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </li>
                        </ul>
                        <small class="label-rating text-muted">132 đánh giá</small>
                        <small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154 đơn hàng </small>
                    </div> <!-- rating-wrap.// -->
                    <div class="mb-3">
                        <var class="price">@Model.Price.ToString("C0", System.Globalization.CultureInfo.GetCultureInfo("vi-VN"))</var>
                    </div> <!-- price-detail-wrap .// -->
                    <p>
                        @Model.ShortDescription
                    </p>

                    <dl class="row">
                        <dt class="col-sm-3">Nhà sản xuất</dt>
                        <dd class="col-sm-9"><a href="#">Great textile Ltd.</a></dd>
                        <dt class="col-sm-3">Số mã sản phẩm</dt>
                        <dd class="col-sm-9">596 065</dd>
                        <dt class="col-sm-3">Bảo hành</dt>
                        <dd class="col-sm-9">2 năm</dd>
                        <dt class="col-sm-3">Thời gian giao hàng</dt>
                        <dd class="col-sm-9">3-4 ngày</dd>
                        <dt class="col-sm-3">Tình trạng</dt>
                        <dd class="col-sm-9">Còn hàng</dd>
                    </dl>
                    <div class="form-row mt-4">
                        <div class="form-group col-md flex-grow-0">
                            <div class="input-group mb-3 input-spinner">
                                <input type="text" id="ipQuantity" class="form-control" value="1">
                            </div>
                        </div> <!-- col.// -->
                        <div class="form-group col-md">
                            <a id="addtocart" class="btn btn-primary">
                                <i class="fas fa-shopping-cart"></i>
                                <span class="text">Thêm vào giỏ hàng</span>
                            </a>
                        </div> <!-- col.// -->
                    </div> <!-- row.// -->
                </article> <!-- product-info-aside .// -->
            </main> <!-- col.// -->
        </div> <!-- row.// -->
        <!-- ================ ITEM DETAIL END .// ================= -->

    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y bg">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h5 class="title-description">Mô tả</h5>
                @Model.FullDescription
            </div> <!-- col.// -->

            <aside class="col-md-4">
                <div class="box">

                    <h5 class="title-description">Tài liệu</h5>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <h5 class="title-description">Video</h5>
                    <article class="media mb-3">
                        <a href="#"><img class="img-sm mr-3" src="~/Content/images/posts/2.jpg"></a>
                        <div class="media-body">
                            <h6 class="mt-0"><a href="#">Mẹo và thủ thuật mới</a></h6>
                            <p class="mb-2"> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin </p>
                        </div>
                    </article>
                    <article class="media mb-3">
                        <a href="#"><img class="img-sm mr-3" src="~/Content/images/posts/1.jpg"></a>
                        <div class="media-body">
                            <h6 class="mt-0"><a href="#">Mẹo và thủ thuật mới</a></h6>
                            <p class="mb-2"> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin </p>
                        </div>
                    </article>
                </div> <!-- box.// -->
            </aside> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
<!-- ========================= SECTION SUBSCRIBE  ========================= -->
<section class="padding-y-lg bg-light border-top">
    <div class="container">
        <p class="pb-2 text-center">Cập nhật những xu hướng sản phẩm và tin tức ngành mới nhất vào hộp thư của bạn</p>
        <div class="row justify-content-md-center">
            <div class="col-lg-4 col-sm-6">
                <form class="form-row">
                    <div class="col-8">
                        <input class="form-control" placeholder="Email của bạn" type="email">
                    </div> <!-- col.// -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-block btn-warning"> <i class="fa fa-envelope"></i> Đăng ký </button>
                    </div> <!-- col.// -->
                </form>
                <small class="form-text text-muted text-center">Chúng tôi không bao giờ chia sẻ email của bạn với bất kỳ ai khác.</small>
            </div>
        </div> <!-- row.// -->
    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION SUBSCRIBE END ========================= -->